apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    component: {{ .Chart.Name }}
spec:
  replicas: {{ pluck .Values.global.env .Values.replicas.nginx | first | default .Values.replicas.nginx._default }}
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: nginx
{{ tuple "nginx" . | include "werf_container_image" | indent 8 }}
        #command: ["nginx", "-g", "daemon off;"]
        #workingDir: "/"
        ports:
        - containerPort: {{ pluck .Values.global.env .Values.app.nginx.rest_port | first | default .Values.app.nginx.rest_port._default }}
          name: http
          protocol: TCP
        env:
{{ tuple "nginx" . | include "werf_container_env" | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    component: {{ .Chart.Name }}
  ports:
  - name: http
    port: {{ pluck .Values.global.env .Values.app.nginx.rest_port | first | default .Values.app.nginx.rest_port._default }}
